spring.application.name=gateway-service
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8888/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Logs the HTTP server (incoming) traffic
spring.cloud.gateway.httpserver.wiretap=true
# Logs the HTTP client (outgoing) traffic
spring.cloud.gateway.httpclient.wiretap=true

# Ensure reactor netty logs are visible
logging.level.reactor.netty=DEBUG
